In [2]:
import numpy as np
lista1= [1,2,3,4,5]
arreglo1= np.array(lista1)
arreglo1

array([1, 2, 3, 4, 5])

In [6]:
type(arreglo1)

numpy.ndarray

In [10]:
lista2=[[1,2,3],[4,5,6],[7,8,9]]
arreglo2=np.array(lista2)
arreglo2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
lista=["a",True,1]
lista

['a', True, 1]

In [14]:
arreglo3=np.zeros((5,4))
arreglo3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.random.random((3,2))

array([[0.15987053, 0.43481053],
       [0.24134036, 0.20264264],
       [0.71157911, 0.21591945]])

In [18]:
np.arange(-2,7)

array([-2, -1,  0,  1,  2,  3,  4,  5,  6])

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [22]:
arreglo1= np.array([[1,2],[5,7]])
arreglo2= np.array([[8,9],[5,7]])
arreglo3= np.array([[1,2],[5,7]])

In [24]:
arreglo4=np.array([arreglo1,arreglo2,arreglo3])
arreglo4

array([[[1, 2],
        [5, 7]],

       [[8, 9],
        [5, 7]],

       [[1, 2],
        [5, 7]]])

In [26]:
arreglo3.shape

(2, 2)

In [28]:
lista2= [[1,2,3],[4,5,6],[7,8,9]]
arreglo2=np.array(lista2)
arreglo2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arreglo2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arreglo= np.array([[1,2],[3,4],[5,6]])
arreglo.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.array([1.25,2.43,200.88]).dtype

dtype('float64')

In [41]:
arreglo_string=np.array(["Introduccion","a","la","programacion"])
arreglo_string.dtype

dtype('<U12')

In [45]:
arreglo=np.array([1.25,2.43,200.88],dtype=np.float32)
arreglo.dtype

dtype('float32')

In [53]:
arreglo_boolean= np.array([True,False],dtype=np.bool_)
arreglo_boolean.dtype

dtype('bool')

In [55]:
arreglo_boolean2= arreglo_boolean.astype(np.int32)
arreglo_boolean2

array([1, 0])

In [57]:
np.array([0,50,50.8]).dtype

dtype('float64')

In [59]:
np.array([0,False,42]).dtype

dtype('int32')