In [2]:
import numpy as np
accidentes= np.array([[0,1,1],[1,0,1],[1,3,2],[2,2,0]])
accidentes.sum()

14

In [4]:
accid_areas=accidentes.sum(axis=0)
accid_areas

array([4, 6, 4])

In [8]:
print("Los accidentes del área 1: ",accid_areas[0])
print("Los accidentes del área 1: ",accid_areas[1])
print("Los accidentes del área 1: ",accid_areas[2])

Los accidentes del área 1:  4
Los accidentes del área 1:  6
Los accidentes del área 1:  4


In [14]:
accid_anios=accidentes.sum(axis=1,keepdims=True)
accid_anios

array([[2],
       [2],
       [6],
       [4]])

In [18]:
print("Los accidentes del área 1: ",accid_anios[0])
print("Los accidentes del área 2: ",accid_anios[1])
print("Los accidentes del área 3: ",accid_anios[2])
print("Los accidentes del área 4: ",accid_anios[3])

Los accidentes del área 1:  [2]
Los accidentes del área 2:  [2]
Los accidentes del área 3:  [6]
Los accidentes del área 4:  [4]


In [22]:
maximo=accidentes.max()
minimo=accidentes.min()
print(f"Máximo de accidentes: {maximo}")
print(f"Mínimo de accidentes: {minimo}")

Máximo de accidentes: 3
Mínimo de accidentes: 0


In [24]:
promedio = accidentes.mean()
print(f"Promedio de accidentes: {promedio}")

Promedio de accidentes: 1.1666666666666667


In [3]:

arreglo= np.array([[1,2,3],[4,5,6]])
dimensiones=arreglo.shape
print(dimensiones[0])
print(dimensiones[1])
print(arreglo[0][0])

NameError: name 'np' is not defined

In [34]:
import time
inicio= time.time()
arreglo_final=np.zeros((2,3))

for renglon in range(dimensiones[0]):
    for columna in range(dimensiones[1]):
        arreglo_final[renglon][columna]= arreglo_final[renglon][columna] + 3
print(arreglo_final)

fin=time.time()
print("Tiempo total de ejecución (segs)", fin - inicio)

[[3. 3. 3.]
 [3. 3. 3.]]
Tiempo total de ejecución (segs) 0.029935359954833984


In [36]:
import time
inicio= time.time()

arreglo_final=arreglo + 3
print(arreglo_final)

fin= time.time()
print("Tiempo total de ejecución (segs)", fin - inicio)

[[4 5 6]
 [7 8 9]]
Tiempo total de ejecución (segs) 0.01628851890563965


In [5]:
import numpy as np
arreglo= np.array([[1,2,3],[4,5,6]])
arreglo_prod=arreglo * 3
arreglo_prod

array([[ 3,  6,  9],
       [12, 15, 18]])

In [7]:
arreglo1=np.array([[1,2,3],[4,5,6]])
arreglo2=np.array([[7,8,9],[10,11,12]])
arreglo3= arreglo1+arreglo2
arreglo3

array([[ 8, 10, 12],
       [14, 16, 18]])

In [11]:
arreglo1 >2

array([[False, False,  True],
       [ True,  True,  True]])

In [15]:
arreglo= np.array(["Numpy","maneja","vectorizacion"])
len(arreglo)>5

False

In [21]:
len_vectorizada= np.vectorize(len)
len_vectorizada(arreglo)>5

array([False,  True,  True])

In [23]:
arreglo= np.arange(10).reshape((2,5))
arreglo

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
arreglo + np.array([0,1,2,3,4])

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [29]:
arreglo= np.arange(10).reshape((2,5))
arreglo + np.array([0,1]).reshape((2,1))

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [31]:
arreglo= np.array([[1.1,1.2,1.3],[2.1,2.2,2.3],[4.1,4.2,4.3]])
np.flip(arreglo)

array([[4.3, 4.2, 4.1],
       [2.3, 2.2, 2.1],
       [1.3, 1.2, 1.1]])

In [33]:
arreglo= np.array([[1.1,1.2,1.3],[2.1,2.2,2.3],[4.1,4.2,4.3]])
np.transpose(arreglo)

array([[1.1, 2.1, 4.1],
       [1.2, 2.2, 4.2],
       [1.3, 2.3, 4.3]])

In [37]:
np.array([[1,2],[3,4]]) * np.array([[5],[10]])
arreglo

array([[ 5, 10],
       [30, 40]])

In [43]:
np.array([[1,2],[3,4]]) - np.array([[5,10]])

array([[-4, -8],
       [-2, -6]])