In [2]:
import numpy as np
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x[2]

2

In [6]:
x[-2]

8

In [8]:
x.shape=(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
x[1,3]

8

In [12]:
x[1][3]

8

In [14]:
x[1][-1]

9

In [16]:
x[0]

array([0, 1, 2, 3, 4])

In [18]:
x=np.array([0,1,2,3,4,5,6,7,8,9])
x[1:7:2]

array([1, 3, 5])

In [20]:
x[-2:10]

array([8, 9])

In [22]:
x[-3:3:-1]

array([7, 6, 5, 4])

In [28]:
x=np.arange(10,1,-1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [30]:
x[np.array([3,3,1,8])]

array([7, 7, 9, 2])

In [32]:
x[np.array([3,3,-3,8])]

array([7, 7, 4, 2])

In [34]:
y=np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [36]:
y[np.array([0,2,4]),np.array([0,1,2])]

array([ 0, 15, 30])

#Union de arrelos

In [38]:
arr= np.concatenate([[1,2,3],[4,5,6]])
arr

array([1, 2, 3, 4, 5, 6])

In [40]:
np.stack([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
mat_1=np.array([[1,2,3],[4,5,6]])
mat_2=np.array([[1,1,1],[2,2,2]])
np.concatenate((mat_1,mat_2),axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [2, 2, 2]])

In [44]:
np.concatenate((mat_1,mat_2),axis=1)

array([[1, 2, 3, 1, 1, 1],
       [4, 5, 6, 2, 2, 2]])

In [46]:
np.concatenate((mat_1,mat_2),axis=None)

array([1, 2, 3, 4, 5, 6, 1, 1, 1, 2, 2, 2])